---
title: "06_RawDataVisualisation"
output: pdf_document
author: ""
date: "2025-03-06"
editor_options: 
  chunk_output_type: console
---

# Create Figure of Raw Data Examples

```{r}
ValencePlot_1 <- ggplot(filter(d_T1_multivariate, CoupleID == 47), aes(x = time)) +
    geom_line(aes(y = MotherValence * 100, color = "Mother"), size = 1) +
    geom_line(aes(y = FatherValence * 100, color = "Father"), size = 1) +
    geom_point(aes(y = MotherValence * 100, color = "Mother"), size = 3) +
    geom_point(aes(y = FatherValence * 100, color = "Father"), size = 3) +
    geom_vline(xintercept = seq(7, 38, by = 6), linetype = "dashed", alpha = 0.3) +
    scale_color_manual(values = c("#21908CFF", "#D95F02")) +
    scale_y_continuous(limits = c(0, 100), breaks = seq(0, 100, 25)) +
    scale_x_continuous(breaks = seq(1, 42, by = 6), labels = c("Day 1", "Day 2", "Day 3", "Day 4", "Day 5", "Day 6", "Day 7")) +
    theme_minimal() +
    labs(title = "Time Series Data",
         y = "Valence",
         x = "",
         color = "Partner") +
    theme(plot.title = element_text(hjust = 0.5, size = 20, face = "bold"),
          axis.text.x = element_blank(),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 20, color = "black"),
          axis.title.y = element_text(size = 20),
          legend.title = element_blank(),
          legend.text = element_text(size = 20),
          legend.key.size = unit(3, "lines"),
          legend.key = element_rect(fill = "transparent", color = NA),
          legend.background = element_rect(fill = "transparent", color = NA),
          legend.position = "none",
          strip.background = element_rect(color = "white", fill = "white", linewidth = 1.5, linetype = "solid"),
          strip.text.x = element_text(size = 20, color = "black", face ="bold"),
          panel.grid.minor.y = element_blank(),
          panel.grid.major.x = element_blank(),
          panel.grid.minor.x = element_blank())

ValencePlot_2 <- ggplot(filter(d_T1_multivariate, CoupleID == 127), aes(x = time)) +
    geom_line(aes(y = MotherValence * 100, color = "Mother"), size = 1) +
    geom_line(aes(y = FatherValence * 100, color = "Father"), size = 1) +
    geom_point(aes(y = MotherValence * 100, color = "Mother"), size = 3) +
    geom_point(aes(y = FatherValence * 100, color = "Father"), size = 3) +
    geom_vline(xintercept = seq(7, 38, by = 6), linetype = "dashed", alpha = 0.3) +
    scale_color_manual(values = c("#21908CFF", "#D95F02")) +
    scale_y_continuous(limits = c(0, 100), breaks = seq(0, 100, 25)) +
    #scale_x_continuous(limits = c(0, 42), breaks = seq(0, 42, 5)) +
    scale_x_continuous(breaks = seq(1, 42, by = 6), labels = c("Day 1", "Day 2", "Day 3", "Day 4", "Day 5", "Day 6", "Day 7")) +
    theme_minimal() +
    labs(title = "Couple 2",
         y = "Valence",
         x = "",
         color = "Partner") +
    theme(plot.title = element_blank(),
          axis.text.x = element_blank(),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 20, color = "black"),
          axis.title.y = element_text(size = 20),
          legend.title = element_blank(),
          legend.text = element_text(size = 20),
          legend.key.size = unit(3, "lines"),
          legend.key = element_rect(fill = "transparent", color = NA),
          legend.background = element_rect(fill = "transparent", color = NA),
          legend.position = "none",
          strip.background = element_rect(color = "white", fill = "white", linewidth = 1.5, linetype = "solid"),
          strip.text.x = element_text(size = 20, color = "black", face ="bold"),
          panel.grid.minor.y = element_blank(),
          panel.grid.major.x = element_blank(),
          panel.grid.minor.x = element_blank())

ValencePlot_3 <- ggplot(filter(d_T1_multivariate, CoupleID == 52), aes(x = time)) +
    geom_line(aes(y = MotherValence * 100, color = "Mother"), size = 1) +
    geom_line(aes(y = FatherValence * 100, color = "Father"), size = 1) +
    geom_point(aes(y = MotherValence * 100, color = "Mother"), size = 3) +
    geom_point(aes(y = FatherValence * 100, color = "Father"), size = 3) +
    geom_vline(xintercept = seq(7, 38, by = 6), linetype = "dashed", alpha = 0.3) +
    scale_color_manual(values = c("#21908CFF", "#D95F02")) +
    scale_y_continuous(limits = c(0, 100), breaks = seq(0, 100, 25)) +
    #scale_x_continuous(limits = c(0, 42), breaks = seq(0, 42, 5)) +
    scale_x_continuous(breaks = seq(1, 42, by = 6), labels = c("Day 1", "Day 2", "Day 3", "Day 4", "Day 5", "Day 6", "Day 7")) +
    theme_minimal() +
    labs(title = "Couple 3",
         y = "Valence",
         x = "",
         color = "Partner") +
    guides(color = guide_legend(nrow = 1)) +
    theme(plot.title = element_blank(),
          axis.text.x = element_text(size = 20, color = "black"),
          axis.title.x = element_text(size = 20),
          axis.text.y = element_text(size = 20, color = "black"),
          axis.title.y = element_text(size = 20),
          legend.title = element_blank(),
          legend.text = element_text(size = 20),
          legend.key.size = unit(2, "lines"),
          legend.key = element_rect(fill = "transparent", color = NA),
          legend.background = element_rect(fill = "transparent", color = NA),
          legend.position = c(0.7, 2.5),
          legend.box = "horizontal",
          strip.background = element_rect(color = "white", fill = "white", linewidth = 1.5, linetype = "solid"),
          strip.text.x = element_text(size = 20, color = "black", face ="bold"),
          panel.grid.minor.y = element_blank(),
          panel.grid.major.x = element_blank(),
          panel.grid.minor.x = element_blank())

VisualAbstractFigure <- plot_grid(ValencePlot_1, ValencePlot_2, ValencePlot_3, 
                                  nrow = 3, rel_heights = c(0.36, 0.33, 0.333))

#ggsave(plot = VisualAbstractFigure, filename = here("FinalFigures", "VisualAbstractFigure.pdf"), height = 10, width = 10)
```

```{r}
# Create a mapping for couple IDs with periods based on days
d_split <- d_T1_multivariate %>%
  group_by(CoupleID) %>%
  mutate(
    period = case_when(
      time <= 18 ~ "Days 1-3",  # First 18 pings (3 days)
      time <= 30 ~ "Days 4-5",  # Next 12 pings (2 days)
      TRUE ~ "Days 6-7"         # Last 12 pings (2 days)
    ),
    period = factor(period, levels = c("Days 1-3", "Days 4-5", "Days 6-7")),
    CoupleLabel = case_when(
      CoupleID == 47 ~ "Couple 1",
      CoupleID == 127 ~ "Couple 2",
      CoupleID == 52 ~ "Couple 3"
    ))

ValenceArousalRawData_1 <- ggplot() +
    facet_grid(CoupleLabel ~ period) +  # Use CoupleLabel instead of CoupleID
    geom_path(data = filter(d_split, CoupleID %in% c(52)), 
              aes(y = MotherValence * 100, x = MotherArousal * 100, color = "Mother"), 
              size = 1) +
    geom_path(data = filter(d_split, CoupleID %in% c(52)), 
              aes(y = FatherValence * 100, x = FatherArousal * 100, color = "Father"), 
              size = 1) +
    geom_point(data = filter(d_split, CoupleID %in% c(52)), 
               aes(y = MotherValence * 100, x = MotherArousal * 100, color = "Mother"), 
               size = 2) +
    geom_point(data = filter(d_split, CoupleID %in% c(52)), 
               aes(y = FatherValence * 100, x = FatherArousal * 100, color = "Father"), 
               size = 2) +
    scale_color_manual(values = c("#21908CFF", "#D95F02")) +
    scale_y_continuous(limits = c(0, 100), breaks = seq(0, 100, 25)) +
    scale_x_continuous(limits = c(0, 100), breaks = seq(0, 75, 25)) +
    theme_minimal() +
    labs(y = "Valence",
         x = "Arousal",
         color = "Partner") +
  theme(plot.title = element_text(hjust = 0.5, size = 20, face ="bold"),
          axis.text.x = element_text(size = 20, color = "black"),
          axis.title.x = element_text(size = 20),
          axis.text.y = element_text(size = 20, color = "black"),
          axis.title.y = element_text(size = 20),
          legend.title = element_blank(),
          legend.text = element_text(size = 20),
          legend.key.size = unit(2, "lines"),
          legend.key = element_rect(fill = "transparent", color = NA),
          legend.background = element_rect(fill = "transparent", color = NA),
          legend.position = "none",
          legend.box = "horizontal",
          strip.background = element_rect(color = "white", fill = "white", linewidth = 1.5, linetype = "solid"),
          strip.text.x = element_blank(),
          strip.text.y = element_text(size = 20, color = "black", face = "bold"),
          panel.grid.minor.y = element_blank(),
          #panel.grid.major.x = element_blank(),
          #panel.grid.major.y = element_blank(),
          panel.grid.minor.x = element_blank())

ValenceArousalRawData_2 <- ggplot() +
    facet_grid(CoupleLabel ~ period) +  # Use CoupleLabel instead of CoupleID
    geom_path(data = filter(d_split, CoupleID %in% c(127)), 
              aes(y = MotherValence * 100, x = MotherArousal * 100, color = "Mother"), 
              size = 1) +
    geom_path(data = filter(d_split, CoupleID %in% c(127)), 
              aes(y = FatherValence * 100, x = FatherArousal * 100, color = "Father"), 
              size = 1) +
    geom_point(data = filter(d_split, CoupleID %in% c(127)), 
               aes(y = MotherValence * 100, x = MotherArousal * 100, color = "Mother"), 
               size = 2) +
    geom_point(data = filter(d_split, CoupleID %in% c(127)), 
               aes(y = FatherValence * 100, x = FatherArousal * 100, color = "Father"), 
               size = 2) +
    scale_color_manual(values = c("#21908CFF", "#D95F02")) +
    scale_y_continuous(limits = c(0, 100), breaks = seq(0, 100, 25)) +
    scale_x_continuous(limits = c(0, 100), breaks = seq(0, 75, 25)) +
    theme_minimal() +
    labs(y = "Valence",
         x = "Arousal",
         color = "Partner") +
  theme(plot.title = element_text(hjust = 0.5, size = 20, face ="bold"),
          axis.text.x = element_blank(),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 20, color = "black"),
          axis.title.y = element_text(size = 20),
          legend.title = element_blank(),
          legend.text = element_text(size = 20),
          legend.key.size = unit(2, "lines"),
          legend.key = element_rect(fill = "transparent", color = NA),
          legend.background = element_rect(fill = "transparent", color = NA),
          legend.position = "none",
          legend.box = "horizontal",
          strip.background = element_rect(color = "white", fill = "white", linewidth = 1.5, linetype = "solid"),
          strip.text.x = element_blank(),
          strip.text.y = element_text(size = 20, color = "black", face = "bold"),
          panel.grid.minor.y = element_blank(),
          #panel.grid.major.x = element_blank(),
          #panel.grid.major.y = element_blank(),
          panel.grid.minor.x = element_blank())

ValenceArousalRawData_3 <- ggplot() +
    facet_grid(CoupleLabel ~ period) +  # Use CoupleLabel instead of CoupleID
    geom_path(data = filter(d_split, CoupleID %in% c(47)), 
              aes(y = MotherValence * 100, x = MotherArousal * 100, color = "Mother"), 
              size = 1) +
    geom_path(data = filter(d_split, CoupleID %in% c(47)), 
              aes(y = FatherValence * 100, x = FatherArousal * 100, color = "Father"), 
              size = 1) +
    geom_point(data = filter(d_split, CoupleID %in% c(47)), 
               aes(y = MotherValence * 100, x = MotherArousal * 100, color = "Mother"), 
               size = 2) +
    geom_point(data = filter(d_split, CoupleID %in% c(47)), 
               aes(y = FatherValence * 100, x = FatherArousal * 100, color = "Father"), 
               size = 2) +
    scale_color_manual(values = c("#21908CFF", "#D95F02")) +
    scale_y_continuous(limits = c(0, 100), breaks = seq(0, 100, 25)) +
    scale_x_continuous(limits = c(0, 100), breaks = seq(0, 75, 25)) +
    theme_minimal() +
    labs(y = "Valence",
         x = "Arousal",
         color = "Partner") +
  theme(plot.title = element_text(hjust = 0.5, size = 20, face ="bold"),
          axis.text.x = element_blank(),
          axis.title.x = element_blank(),
          axis.text.y = element_text(size = 20, color = "black"),
          axis.title.y = element_text(size = 20),
          legend.title = element_blank(),
          legend.text = element_text(size = 20),
          legend.key.size = unit(2, "lines"),
          legend.key = element_rect(fill = "transparent", color = NA),
          legend.background = element_rect(fill = "transparent", color = NA),
          legend.position = "none",
          legend.box = "horizontal",
          strip.background = element_rect(color = "white", fill = "white", linewidth = 1.5, linetype = "solid"),
          strip.text.x = element_text(size = 20, color = "black", face = "bold"),
          strip.text.y = element_text(size = 20, color = "black", face = "bold"),
          panel.grid.minor.y = element_blank(),
          #panel.grid.major.x = element_blank(),
          #panel.grid.major.y = element_blank(),
          panel.grid.minor.x = element_blank())
```

# Combine Figures
```{r}
ValenceArousal <- plot_grid(ValenceArousalRawData_3, ValenceArousalRawData_2, ValenceArousalRawData_1, 
                            nrow = 3, rel_heights = c(0.36, 0.33, 0.333))

VisualAbstractFigure_join <- plot_grid(NULL, VisualAbstractFigure, nrow = 2, rel_heights = c(0.0, 0.98))
RawDataPlot <- plot_grid(VisualAbstractFigure_join, ValenceArousal, ncol = 2, align = "vh")
RawDataPlot
#ggsave(plot = RawDataPlot, filename = here("FinalFigures", "RawDataPlot.pdf"), height = 10, width = 14)
```


